### ISSUE TITLE
The extension has been removed from Firefox Add-ons?

### ISSUE THREAD

**Issue by xnuk** [parksb/multilingual-fox#14]
!["이런! 페이지를 찾을 수 없습니다." 내용이 뜨는 multilingual-fox 애드온 페이지](https://user-images.githubusercontent.com/3071003/154782249-2f5b8ed4-4517-4633-ab54-3d588648d2e3.png)

<details><summary>Text in image</summary>

> ## 이런! 페이지를 찾을 수 없습니다.
>
> 다른 웹사이트에서 부가 기능이나 테마 링크로 오신 경우, 해당 항목은 더이상 사용할 수 없습니다. 이는 다음과 같은 이유일 수 있습니다:
>
> - 개발자가 항목을 제거하였습니다. 개발자들은 일반적으로 부가 기능이나 테마를 더이상 지원하지 않거나 대체하기 위해서 이렇게 합니다.
> - Mozilla가 제거한 것입니다. 이는 부가 기능이나 테마의 검토 과정에서 문제가 발생했거나, addons.mozilla.org의 이용 약관을 위반한 경우입니다. 개발자는 문제를 해결하고 부가 기능을 다시 내려받을 수 있도록 할 수 있습니다.
>
> 나중에 페이지를 다시 방문해 주세요. 테마나 확장 기능 이용이 가능해질 수도 있습니다. 그 대신에, 사용 가능한 [확장 기능들](https://addons.mozilla.org/ko/firefox/extensions/) 또는 [테마들](https://addons.mozilla.org/ko/firefox/themes/), 또는 [커뮤니티 포럼](https://discourse.mozilla.org/c/add-ons)에 도움을 요청함으로써 원하는 내용을 찾아볼 수 있습니다.

</details>

**Comment by parksb** [comment]
애드온 리뷰에서 '제출된 코드와 빌드된 코드가 다르다'는 이유로 리젝되고 있습니다. 현재 빌드 결과물(`dist/index.js`, `dist/index.js.map`)에 빌드 실행 위치에 따른 경로가 포함되고 있는데, 이로 인한 차이로 추정하고 있습니다.

**Comment by parksb** [comment]
#20 #19 이슈 반영 후 0.4.0 버전으로 제출 예정입니다. 제보 및 PR 감사합니다🙂

**Comment by parksb** [comment]
https://addons.mozilla.org/addon/multilingual-fox/ 다시 올라왔습니다!
