### ISSUE TITLE
일부 단어의 경우 첫 번째 결과에 뜻풀이가 없습니다

### ISSUE THREAD

**Issue by xnuk** [parksb/multilingual-fox#29]
|              | intrinsically                      | accidentally                       |
|--------------|------------------------------------|------------------------------------|
| 네이버 영어사전 | ![intrinsically - 네이버 영어사전]     | ![accidentally - 네이버 영어사전]     |
| 다국어 여우    | ![intrinsically - Multilingual Fox] | ![accidentally - Multilingual Fox] |

[intrinsically - 네이버 영어사전]: https://github.com/parksb/multilingual-fox/assets/3071003/51d0f3e2-488a-4eba-b9ee-8579f6da9a71
[accidentally - 네이버 영어사전]: https://github.com/parksb/multilingual-fox/assets/3071003/1e86e022-c57b-4ad5-9512-419466af4835
[intrinsically - Multilingual Fox]: https://github.com/parksb/multilingual-fox/assets/3071003/f0aeb552-c00f-43ed-89e1-d9ee04cddb5f
[accidentally - Multilingual Fox]: https://github.com/parksb/multilingual-fox/assets/3071003/9741ea5f-5c4d-4cf1-bb19-a716785637f2

엄밀히 말하자면 네이버 영어사전의 문제이긴 합니다. "intrinsically"나 "accidentally" 같은 '형용사 + -ly' 형태의 부사에서 많이 일어나는 현상인 듯합니다. 뜻풀이가 없고 예문만 있어서, 단어의 정확한 의미를 파악하려면 스크롤해야 하는 불편함이 있습니다. `mean.value === null` (또는 `description === undefined`)일 때 따로 처리를 해줄 거 같은데, 이걸 지우는 게 좋을까요 아니면 결과 중에서 맨 밑으로 보내는 게 좋을까요

**Comment by parksb** [comment]
뜻풀이가 없는 경우 맨 아래에 노출하는게 좋을 것 같네요.
