### ISSUE TITLE
트리거 키 기본값이 `Alt` 키가 아닌 듯합니다.

### ISSUE THREAD

**Issue by xnuk** [parksb/multilingual-fox#31]
https://github.com/parksb/multilingual-fox/blob/e0427bb72160e55a64ee8e7508b9c31b97f10ad4/index.ts#L22-L24

최근 업데이트에 코드가 반영된 거 같은데, 이 코드 때문인지 기본적으로 `Alt` 키 없이 텍스트만 선택해도 네이버 사전이 열리는 듯합니다. 설정창과 extension 자체의 description이 `Alt` 키가 기본이라고 설명되어 있는 것을 차치하더라도, 아무 설정 없이 사용하면 텍스트 선택만으로도 의도치 않게 네이버 서버에 값이 전송되어 약간의 privacy 문제가 있지 않을까... 라고 한 10초 정도 생각했습니다.

**Comment by parksb** [comment]
앗 그럴 수 있겠네요! 리포트 감사합니다 :)
