### ISSUE TITLE
예문 안의 <ruby> 태그 지원? HTML 삽입?

### ISSUE THREAD

**Issue by xnuk** [parksb/multilingual-fox#34]
![image](https://github.com/user-attachments/assets/9fc31f94-10b7-424b-bbaf-f7aba3370189)

```json
{
  "value": "갑자기, 돌연, 느닷없이.",
  "exampleOri": "&lt;ruby&gt;&lt;rb&gt;行&lt;/rb&gt;&lt;rt&gt;い&lt;/rt&gt;&lt;/ruby&gt;き&lt;ruby&gt;&lt;rb&gt;成&lt;/rb&gt;&lt;rt&gt;な&lt;/rt&gt;&lt;/ruby&gt;り&lt;ruby&gt;&lt;rb&gt;訪&lt;/rb&gt;&lt;rt&gt;たず&lt;/rt&gt;&lt;/ruby&gt;ねてくる",
  "exampleTrans": "느닷없이 찾아오다"
}
```

예문에서만 나타나는 거 같아서 아직까지는 괜찮은데 마주칠 때마다 당황스럽긴 합니다

**Comment by parksb** [comment]
v0.5.4에서 루비 문자가 보이도록 수정했는데, 제가 일본어 사전을 쓸 일이 잘 없다보니... 관련해서 문제가 또 발견될 수 있으니 한동안 이슈는 안 닫겠습니다😅

**Comment by xnuk** [comment]
![image](https://github.com/user-attachments/assets/5d98e9ef-d378-46fb-96b1-6df5e6131239)
일단은 이쁘게 보이긴 하네요
